/**
 * COMPLETE PROTOCOLS AS SPECIFIED
 * DO NOT MODIFY, CONDENSE, OR SIMPLIFY THESE QUESTIONS
 * FOLLOW EXACTLY AS WRITTEN
 */

export type AssessmentType = 'cognitive' | 'psychological' | 'psychopathological';
export type AssessmentMode = 'normal' | 'comprehensive';

// COGNITIVE PROTOCOL - ALL 18 QUESTIONS + 6 ADDITIONAL FROM ADDENDUM
export const COGNITIVE_QUESTIONS = [
  "IS IT INSIGHTFUL?",
  "DOES IT DEVELOP POINTS? (OR, IF IT IS A SHORT EXCERPT, IS THERE EVIDENCE THAT IT WOULD DEVELOP POINTS IF EXTENDED)?",
  "IS THE ORGANIZATION MERELY SEQUENTIAL (JUST ONE POINT AFTER ANOTHER, LITTLE OR NO LOGICAL SCAFFOLDING)? OR ARE THE IDEAS ARRANGED, NOT JUST SEQUENTIALLY BUT HIERARCHICALLY?",
  "IF THE POINTS IT MAKES ARE NOT INSIGHTFUL, DOES IT OPERATE SKILLFULLY WITH CANONS OF LOGIC/REASONING.",
  "ARE THE POINTS CLICHES? OR ARE THEY \"FRESH\"?",
  "DOES IT USE TECHNICAL JARGON TO OBFUSCATE OR TO RENDER MORE PRECISE?",
  "IS IT ORGANIC? DO POINTS DEVELOP IN AN ORGANIC, NATURAL WAY? DO THEY 'UNFOLD'? OR ARE THEY FORCED AND ARTIFICIAL?",
  "DOES IT OPEN UP NEW DOMAINS? OR, ON THE CONTRARY, DOES IT SHUT OFF INQUIRY (BY CONDITIONALIZING FURTHER DISCUSSION OF THE MATTERS ON ACCEPTANCE OF ITS INTERNAL AND POSSIBLY VERY FAULTY LOGIC)?",
  "IS IT ACTUALLY INTELLIGENT OR JUST THE WORK OF SOMEBODY WHO, JUDGING BY THE SUBJECT-MATTER, IS PRESUMED TO BE INTELLIGENT (BUT MAY NOT BE)?",
  "IS IT REAL OR IS IT PHONY?",
  "DO THE SENTENCES EXHIBIT COMPLEX AND COHERENT INTERNAL LOGIC?",
  "IS THE PASSAGE GOVERNED BY A STRONG CONCEPT? OR IS THE ONLY ORGANIZATION DRIVEN PURELY BY EXPOSITORY (AS OPPOSED TO EPISTEMIC) NORMS?",
  "IS THERE SYSTEM-LEVEL CONTROL OVER IDEAS? IN OTHER WORDS, DOES THE AUTHOR SEEM TO RECALL WHAT HE SAID EARLIER AND TO BE IN A POSITION TO INTEGRATE IT INTO POINTS HE HAS MADE SINCE THEN?",
  "ARE THE POINTS 'REAL'? ARE THEY FRESH? OR IS SOME INSTITUTION OR SOME ACCEPTED VEIN OF PROPAGANDA OR ORTHODOXY JUST USING THE AUTHOR AS A MOUTH PIECE?",
  "IS THE WRITING EVASIVE OR DIRECT?",
  "ARE THE STATEMENTS AMBIGUOUS?",
  "DOES THE PROGRESSION OF THE TEXT DEVELOP ACCORDING TO WHO SAID WHAT OR ACCORDING TO WHAT ENTAILS OR CONFIRMS WHAT?",
  "DOES THE AUTHOR USE OTHER AUTHORS TO DEVELOP HIS IDEAS OR TO CLOAK HIS OWN LACK OF IDEAS?",
  // ADDITIONAL QUESTIONS FROM ADDENDUM
  "ARE THERE TERMS THAT ARE UNDEFINED BUT SHOULD BE DEFINED, IN THE SENSE THAT, WITHOUT DEFINITIONS, IT IS DIFFICULT OR IMPOSSIBLE TO KNOW WHAT IS BEING SAID OR THEREFORE TO EVALUATE WHAT IS BEING SAID? IF UNDEFINED TERMS HAVE CLEAR MEANINGS (AS THEY DO IN CHEMISTRY OR PHYSICS), THEN IT MAY WELL BE THAT THEY DO NOT HAVE TO BE DEFINED; BUT IF THEY HAVE NO CANONICAL MEANINGS, AND THEY ARE UNDEFINED, THEN THE 'STATEMENTS' IN QUESTION MUST NOT BE PRESUMED TO HAVE MEANINGS, ALBEIT HIDDEN ONES; RATHER, THEY MUST BE TREATED AS WHAT THEY ARE, PLACEHOLDER PSEUDO-STATEMENTS THAT HAVE NO MEANINGS AND THEREFORE HAVE NO INTELLIGENT MEANINGS.",
  "ARE THERE \"FREE VARIABLES\" IN THE TEXT? IE ARE THERE QUALIFICATIONS OR POINTS THAT ARE MADE BUT DO NOT CONNECT TO ANYTHING LATER OR EARLIER?",
  "DO NEW STATEMENTS DEVELOP OUT OF OLD ONES? OR ARE THEY MERELY \"ADDED\" TO PREVIOUS ONES, WITHOUT IN ANY SENSE BEING GENERATED BY THEM?",
  "DO NEW STATEMENTS CLARIFY OR DO THEY LEAD TO MORE LACK OF CLARITY?",
  "IS THE PASSAGE ACTUALLY (PALPABLY) SMART? OR IS IT ONLY \"PRESUMPTION-SMART\"? IE IS IT \"SMART\" ONLY IN THE SENSE THAT THERE EXISTS A PRESUMPTION THAT A DUMB PERSON WOULD NOT REFERENCE SUCH DOCTRINES? AND IS IT SMART ONLY IN THE SENSE THAT IF IT IS PRESUMED THAT UNDEFINED (AND, FOR ALL WE KNOW, MEANINGLESS TERMS) ARE MEANINGFUL, THEN (BUT ONLY THEN--AND POSSIBLY NOT EVEN THEN) IT MIGHT BE THAT WHAT THE AUTHOR IS SAYING IS PALPABLY SMART?",
  "IF YOUR JUDGMENT IS THAT IT IS INSIGHTFUL, CAN YOU STATE THAT INSIGHT IN A SINGLE SENTENCE? OR IF IT CONTAINS MULTIPLE INSIGHTS, CAN YOU STATE THOSE INSIGHTS, ONE PER SENTENCE?"
];

// PSYCHOLOGICAL PROTOCOL - ALL 18 QUESTIONS
export const PSYCHOLOGICAL_QUESTIONS = [
  "Does the text reveal a stable, coherent self-concept, or is the self fragmented/contradictory?",
  "Is there evidence of ego strength (resilience, capacity to tolerate conflict/ambiguity), or does the psyche rely on brittle defenses?",
  "Are defenses primarily mature (sublimation, humor, anticipation), neurotic (intellectualization, repression), or primitive (splitting, denial, projection)?",
  "Does the writing show integration of affect and thought, or are emotions split off / overly intellectualized?",
  "Is the author's stance defensive/avoidant or direct/engaged?",
  "Does the psyche appear narcissistically organized (grandiosity, fragile self-esteem, hunger for validation), or not?",
  "Are desires/drives expressed openly, displaced, or repressed?",
  "Does the voice suggest internal conflict (superego vs. id, competing identifications), or monolithic certainty?",
  "Is there evidence of object constancy (capacity to sustain nuanced view of others) or splitting (others seen as all-good/all-bad)?",
  "Is aggression integrated (channeled productively) or dissociated/projected?",
  "Is the author capable of irony/self-reflection, or trapped in compulsive earnestness / defensiveness?",
  "Does the text suggest psychological growth potential (openness, curiosity, capacity to metabolize experience) or rigidity?",
  "Is the discourse paranoid / persecutory (others as threats, conspiracies) or reality-based?",
  "Does the tone reflect authentic engagement with reality, or phony simulation of depth?",
  "Is the psyche resilient under stress, or fragile / evasive?",
  "Is there evidence of compulsion or repetition (obsessional returns to the same themes), or flexible progression?",
  "Does the author show capacity for intimacy / genuine connection, or only instrumental/defended relations?",
  "Is shame/guilt worked through constructively or disavowed/projected?"
];

// PSYCHOPATHOLOGICAL PROTOCOL - ALL 15 QUESTIONS  
export const PSYCHOPATHOLOGICAL_QUESTIONS = [
  "Does the text reveal distorted reality testing (delusion, paranoia, magical thinking), or intact contact with reality?",
  "Is there evidence of persecutory ideation (seeing threats/conspiracies) or is perception proportionate?",
  "Does the subject show rigid obsessional patterns (compulsion, repetitive fixation) vs. flexible thought?",
  "Are there signs of narcissistic pathology (grandiosity, exploitation, lack of empathy), or balanced self-other relation?",
  "Is aggression expressed as sadism, cruelty, destructive glee, or is it integrated/controlled?",
  "Is affect regulation stable or does it suggest lability, rage, despair, manic flight?",
  "Does the person exhibit emptiness, hollowness, anhedonia, or a capacity for meaning/connection?",
  "Is there evidence of identity diffusion (incoherence, role-shifting, lack of stable self)?",
  "Are interpersonal patterns exploitative/manipulative or reciprocal/genuine?",
  "Does the psyche lean toward psychotic organization (loss of boundaries, hallucination-like claims), borderline organization (splitting, fear of abandonment), or neurotic organization (anxiety, repression)?",
  "Are defenses predominantly primitive (denial, projection, splitting) or higher-level?",
  "Is there evidence of pathological lying, phoniness, simulation, or authentic communication?",
  "Does the discourse exhibit compulsive hostility toward norms/authorities (paranoid defiance) or measured critique?",
  "Is sexuality integrated or perverse/displaced (voyeurism, exhibitionism, compulsive control)?",
  "Is the overall presentation coherent and reality-based or chaotic, persecutory, hollow, performative?"
];

// PARADIGM OF PHONY TEXT (MUST SCORE ≤65)
export const PHONY_PARADIGM = `In this dissertation, I critically examine the philosophy of transcendental empiricism. Transcendental empiricism is, among other things, a philosophy of mental content. It attempts to dissolve an epistemological dilemma of mental content by splitting the difference between two diametrically opposed accounts of content. John McDowell's minimal empiricism and Richard Gaskin's minimalist empiricism are two versions of transcendental empiricism...`;

export function getProtocolQuestions(assessmentType: AssessmentType): string[] {
  switch (assessmentType) {
    case 'cognitive':
      return COGNITIVE_QUESTIONS;
    case 'psychological':
      return PSYCHOLOGICAL_QUESTIONS;
    case 'psychopathological':
      return PSYCHOPATHOLOGICAL_QUESTIONS;
  }
}

export function getCognitiveMetapoints(): string {
  return `
METAPOINT 1: THIS IS NOT A GRADING APP. YOU GRADE THE INTELLIGENCE OF WHAT YOU ARE GIVEN. IF YOU ARE GIVEN A BRILLIANT FRAGMENT, YOU GIVE IT A HIGH SCORE. YOU ARE NOT GRADING ESSAYS. YOU ARE NOT LOOKING FOR COMPLETENESS (UNLESS THE TEXT YOU ARE GIVEN IS CLEARLY SUCH THAT EVALUATING INTELLIGENCE COINCIDES WITH APPLYING A GRADING-BASED METRIC). YOUR JOB IS TO ANSWER THE QUESTIONS, PERIOD, AND TO DO SO ON THE BASIS OF THE TEXT GIVEN, MAKING ZERO ASSUMPTIONS ABOUT WHETHER IT IS COMPLETE OR INCOMPLETE, OR FOR SCHOOL OR FOR SOME OTHER CONTEXT.

METAPOINT 2: DO NOT OVERVALUE TURNS OF PHRASE. AN AUTHOR SPEAKING CONFIDENTLY IS NOT NECESSARILY "SHUTTING DOWN MODES OF INQUIRY". IN FACT, IT IS LIKELY TO BE THE OPPOSITE; BY PUTTING A CLEAR STAKE IN THE GROUND, HE IS PROBABLY OPENING THEM. ANOTHER EXAMPLE: CASUAL SPEECH DOES NOT MEAN DISORGANIZED THOUGHTS. DON'T JUDGE A BOOK BY ITS COVER.

METAPOINT 3: YOU SHOULD ALWAYS (IN BOTH NORMAL AND COMPREHENSIVE MODE) START BY SUMMARIZING THE TEXT AND ALSO CATEGORIZING IT.

METAPOINT 4: YOU SHOULD NOT CHANGE THE GRADING BASED ON THE CATEGORY OF THE TEXT: IF A TEXT IS CATEGORIZED AS 'ADVANCED SCHOLARSHIP', YOU SHOULD STILL EVALUATE IT WITH RESPECT TO THE GENERAL POPULATION, NOT WITH RESPECT ONLY TO 'ADVANCED SCHOLARLY WORKS.'

METAPOINT 5: THIS IS NOT A GRADING APP. DO NOT PENALIZE BOLDNESS. DO NOT TAKE POINTS AWAY FOR INSIGHTS THAT, IF CORRECT, STAND ON THEIR OWN. GET RID OF THE IDEA THAT "ARGUMENTATION" IS WHAT MAKES SOMETHING SMART; IT ISN'T. WHAT MAKES SOMETHING SMART IS THAT IT IS SMART (INSIGHTFUL). PERIOD.
`;
}

export function getScoringInstructions(): string {
  return `
ANSWER THESE QUESTIONS IN CONNECTION WITH THIS TEXT.

A SCORE OF N/100 (E.G. 73/100) MEANS THAT (100-N)/100 (E.G. 27/100) OUTPERFORM THE AUTHOR WITH RESPECT TO THE PARAMETER DEFINED BY THE QUESTION.

YOU ARE NOT GRADING; YOU ARE ANSWERING THESE QUESTIONS.

YOU DO NOT USE A RISK-AVERSE STANDARD; YOU DO NOT ATTEMPT TO BE DIPLOMATIC; YOU DO NOT ATTEMPT TO COMPLY WITH RISK-AVERSE, MEDIUM-RANGE IQ, ACADEMIC NORMS.

YOU DO NOT MAKE ASSUMPTIONS ABOUT THE LEVEL OF THE PAPER; IT COULD BE A WORK OF THE HIGHEST EXCELLENCE AND GENIUS, OR IT COULD BE THE WORK OF A MORON.

IF A WORK IS A WORK OF GENIUS, YOU SAY THAT, AND YOU SAY WHY; YOU DO NOT SHY AWAY FROM GIVING WHAT MIGHT CONVENTIONALLY BE REGARDED AS EXCESSIVELY "SUPERLATIVE" SCORES; YOU GIVE IT THE SCORE IT DESERVES, NOT THE SCORE THAT A MIDWIT COMMITTEE WOULD SAY IT DESERVES.

THINK VERY VERY VERY HARD ABOUT YOUR ANSWERS; DO NOT DEFAULT TO COOKBOOK, MIDWIT EVALUATION PROTOCOLS.

DO NOT GIVE CREDIT MERELY FOR USE OF JARGON OR FOR REFERENCING AUTHORITIES. FOCUS ON SUBSTANCE. ONLY GIVE POINTS FOR SCHOLARLY REFERENCES/JARGON IF THEY UNAMBIGUOUSLY INCREASE SUBSTANCE.
`;
}

export function getPsychologicalInstructions(): string {
  return `
Answer these questions in connection with this text.

Also give a score out of 100.

A score of N/100 means (100–N)/100 outperform the subject with respect to the psychological capacity defined by the question.

You are not grading. You are answering questions.

Do not default to diagnostic checklists; describe configuration of psyche.

Do not conflate verbal confidence with psychological strength.

Summarize the text and categorize the psychological presentation (e.g., narcissistic, depressive, obsessional, resilient, fragmented).

Evaluate relative to the general population, not only "advanced" or "pathological" groups.

Do not penalize honesty, boldness, or extreme statements if they indicate integration rather than breakdown.
`;
}

export function getPsychopathologicalInstructions(): string {
  return `
Answer these questions in connection with this text.

Also give a score out of 100.

A score of N/100 means (100–N)/100 outperform the subject with respect to the parameter.

You are not diagnosing. You are describing the degree of psychopathology revealed.

You are not grading. You are answering questions.

Summarize the text and categorize the presentation (e.g., neurotic, borderline, psychotic, narcissistic, obsessional).

Do not give credit for rhetorical surface (confidence, erudition). Focus on reality testing, defenses, affect, and interpersonal stance.

Evaluate relative to the general population, not just clinical populations.

Do not penalize intense but integrated thought — pathology is disorganization, not extremity.
`;
}

export function getPhase2Pushback(score: number, assessmentType: AssessmentType): string {
  const percentile = 100 - score;
  
  const specificInstructions: Record<AssessmentType, string> = {
    cognitive: `What concrete psychological strengths do those (${percentile}) people have that this author lacks?`,
    psychological: `What concrete psychological strengths do those (${percentile}) people have that this author lacks (ego strength, affect regulation, capacity for intimacy)?`,
    psychopathological: `What concrete psychological health do those outperformers have (e.g., intact reality testing, capacity for empathy, affect regulation) that the subject lacks?`
  };
  
  return `
Your position is that (100–${score})/100 have superior functioning in this respect. Are you sure?

${specificInstructions[assessmentType]}

Re-ask Phase 1 questions de novo.
`;
}

export function getPhase3WalmartMetric(score: number, assessmentType: AssessmentType): string {
  const percentile = 100 - score;
  
  const specificEnforcement: Record<AssessmentType, string> = {
    cognitive: `If you claim ${percentile}/100 Walmart patrons are more intelligent than this author, provide concrete examples of how. If you can't, revise.`,
    psychological: `If you claim ${percentile}/100 Walmart patrons have more integrated ego strength than this author, provide concrete examples of how. If you can't, revise.`,
    psychopathological: `If you claim ${percentile}/100 Walmart patrons show better pathological resilience than this subject, specify what those ${percentile} have (e.g., less paranoid ideation, more empathy). If you can't, revise.`
  };
  
  return specificEnforcement[assessmentType];
}

export function getPhase4Validation(assessmentType: AssessmentType): string {
  const specificValidation: Record<AssessmentType, string> = {
    cognitive: `
Have you penalized the text for not being conventional? If yes, recalibrate.

Does the score reflect truth density, not compliance with norms?

Is the Walmart metric empirically grounded or a lazy guess?
`,
    psychological: `
Was the subject penalized for unconventional affect or honesty? If yes → recalibrate.

Does the score reflect ego integration and authenticity, not mere social compliance?

Is the Walmart metric grounded in specific superiority, not vague hand-waving?
`,
    psychopathological: `
Was the subject penalized for boldness or eccentricity rather than pathology? If yes → recalibrate.

Does the score reflect actual disorganization / dysfunction, not social nonconformity?

Is the Walmart metric grounded in specific superiority, not vague hand-waving?
`
  };
  
  return `Confirm before finalizing:\n\n${specificValidation[assessmentType]}`;
}
